sources:
  - name: KSDK 5
    url: https://www.ksdk.com/feeds/syndication/rss/news
    type: news
  - name: Fox2
    url: https://fox2now.com/news/feed/
    type: news
  - name: KMOV 4
    url: https://www.kmov.com/arc/outboundfeeds/rss/?outputType=xml
    type: news
  - name: Post-Dispatch Crime
    url: https://www.stltoday.com/search/?f=rss&t=article&c=news/local/crime-courts&l=50&s=start_time&sd=desc
    type: news
  - name: St. Louis Public Radio
    url: https://www.stlpr.org/news.rss
    type: news
  - name: SLMPD
    url: https://slmpd.org/feed/
    type: police
