"""initial schema

Revision ID: c62cefc9aa3b
Revises: 
Create Date: 2026-10-02 18:10:49.250784

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c62cefc9aa3b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # The sa.Enum(create_constraint=True) columns create their own CHECK constraints.
    # (Autogenerate also listed each one twice as sa.CheckConstraint; SQLite accepted
    # the duplicates, Postgres rejects them, so they were removed.)
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incidents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('crime_type', sa.Enum('shooting', 'burglary', 'homicide', name='crime_type', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('location', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('confirmed', 'review', 'rejected', name='incident_status', native_enum=False, create_constraint=True), server_default='review', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_incidents_occurred_at'), ['occurred_at'], unique=False)

    op.create_table('sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fail_count', sa.Integer(), server_default='0', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_table('raw_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('url_hash', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=1000), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('new', 'classified', 'failed', name='raw_item_status', native_enum=False, create_constraint=True), server_default='new', nullable=False),
    sa.Column('retries', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url_hash')
    )
    with op.batch_alter_table('raw_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_raw_items_status'), ['status'], unique=False)

    op.create_table('classifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('raw_item_id', sa.Integer(), nullable=False),
    sa.Column('is_crime', sa.Boolean(), nullable=False),
    sa.Column('crime_type', sa.Enum('shooting', 'burglary', 'homicide', name='crime_type', native_enum=False, create_constraint=True), nullable=True),
    sa.Column('in_stl', sa.Boolean(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('location', sa.String(length=500), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('prompt_version', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['raw_item_id'], ['raw_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('incident_items',
    sa.Column('incident_id', sa.Integer(), nullable=False),
    sa.Column('raw_item_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.ForeignKeyConstraint(['raw_item_id'], ['raw_items.id'], ),
    sa.PrimaryKeyConstraint('incident_id', 'raw_item_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('incident_items')
    op.drop_table('classifications')
    with op.batch_alter_table('raw_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_raw_items_status'))

    op.drop_table('raw_items')
    op.drop_table('sources')
    with op.batch_alter_table('incidents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_incidents_occurred_at'))

    op.drop_table('incidents')
    # ### end Alembic commands ###
