"""pipeline runs and job locks

Revision ID: e4d4a3446628
Revises: 8e4b2c6d1a70
Create Date: 2026-10-05 00:00:01

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4d4a3446628'
down_revision: Union[str, Sequence[str], None] = '8e4b2c6d1a70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_locks',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('owner', sa.String(length=64), nullable=False),
    sa.Column('acquired_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('pipeline_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('running', 'success', 'partial', 'failed', name='pipeline_run_status', native_enum=False, create_constraint=True), server_default='running', nullable=False),
    sa.Column('fetch_counts', sa.JSON(), nullable=True),
    sa.Column('classify_counts', sa.JSON(), nullable=True),
    sa.Column('match_counts', sa.JSON(), nullable=True),
    sa.Column('fetch_error', sa.Text(), nullable=True),
    sa.Column('classify_error', sa.Text(), nullable=True),
    sa.Column('match_error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pipeline_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pipeline_runs_started_at'), ['started_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pipeline_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pipeline_runs_started_at'))

    op.drop_table('pipeline_runs')
    op.drop_table('job_locks')
    # ### end Alembic commands ###
